included:
  - ExCamera
  - ExCameraTests
  - Utility
  - UtilityTests

excluded:
  - Carthage
  - Pods
  - .bundle
  - ExCamera/R.generated.swift
  - ExCamera/AppResolver.generated.swift

disabled_rules:
  - line_length

variable_name:
  excluded:
    - id
    - x
    - y