name: ExCamera
configs:
  Debug: debug
  Release: release
options:
  defaultConfig: Release
  deploymentTarget: [iOS]
  developmentLanguage: en
  xcodeVersion: 1000
attributes: {
  ORGANIZATIONNAME: '',
}
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 11.0
    SWIFT_VERSION: 4.2
  configs:
    Debug:
      ENABLE_TESTABILITY: YES
      GCC_PREPROCESSOR_DEFINITIONS: DEBUG=1
      MTL_ENABLE_DEBUG_INFO: YES
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      VALIDATE_PRODUCT: NO
    Release:
      ENABLE_TESTABILITY: NO
      MTL_ENABLE_DEBUG_INFO: NO
      VALIDATE_PRODUCT: YES
schemes:
  Development:
    build:
      targets:
        ExCamera: all
    run:
      commandLineArguments:
        "-FIRAnalyticsDebugEnabled": true
      environmentVariables:
        - variable: OS_ACTIVITY_MODE
          value: disable
          isEnabled: false
    test:
      config: Debug
      targets: [ExCameraTests]
    profile:
      config: Debug
    archive:
      config: Debug
  Production:
    build:
      targets:
        ExCamera: all
    run:
      config: Release
      commandLineArguments:
        "-noFIRAnalyticsDebugEnabled": true
      environmentVariables:
        - variable: OS_ACTIVITY_MODE
          value: disable
          isEnabled: false
    test:
      config: Release
      targets: [ExCameraTests]
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
targets:
  ExCamera:
    type: application
    platform: iOS
    sources: ExCamera
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        CODE_SIGN_STYLE: Automatic
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        INFOPLIST_FILE: ExCamera/info.plist
        PRODUCT_NAME: $(TARGET_NAME)
      configs:
        Debug:
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
          DISPLAY_NAME: Camera
          PRODUCT_BUNDLE_IDENTIFIER: me.example.camera
          PROVISIONING_PROFILE_SPECIFIER: match Development me.example.camera
        Release:
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Distribution
          DISPLAY_NAME: Camera
          PRODUCT_BUNDLE_IDENTIFIER: me.example.camera
          PROVISIONING_PROFILE_SPECIFIER: match AppStore me.example.camera
    prebuildScripts:
      - name: Run LicensePlist
        script: ${SRCROOT}/Pods/LicensePlist/license-plist --output-path ExCamera/Settings.bundle
      - name: Run SwiftLint
        script: swiftlint
      - name: Run SwiftGen
        script: swiftgen
      - name: Run DIKitGen
        script: dikitgen ${SRCROOT}/ExCamera --exclude Carthage > ${SRCROOT}/ExCamera/AppResolver.generated.swift
    dependencies:
      - target: Utility
      - carthage: Cartography
      - carthage: DIKit
  Utility:
    type: framework
    platform: iOS
    sources: Utility
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: me.example.camera.utility
      INFOPLIST_FILE: Utility/info.plist
    scheme:
      testTargets:
        - UtilityTests
    dependencies:
      - carthage: XCGLogger
      - carthage: ObjcExceptionBridging
  ExCameraTests:
    type: bundle.unit-test
    platform: iOS
    sources: ExCameraTests
    settings:
      INFOPLIST_FILE: ExCameraTests/info.plist
      CODE_SIGN_STYLE: Automatic
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/ExCamera.app/ExCamera
  UtilityTests:
    type: bundle.unit-test
    platform: iOS
    sources: UtilityTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: me.example.camera.utility-tests
      INFOPLIST_FILE: UtilityTests/Info.plist
      CODE_SIGN_STYLE: Automatic
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/ExCamera.app/ExCamera
    dependencies:
      - target: Utility