name: ExCamera
configs:
  Debug: debug
  AdHoc: release
options:
  developmentLanguage: ja
  defaultConfig: Debug
  minimumXcodeGenVersion: 1.11.2
  xcodeVersion: 10.0
settings:
  IPHONEOS_DEPLOYMENT_TARGET: 11.0
  SDKROOT: iphoneos
  CODE_SIGN_IDENTITY: iPhone Developer
  SWIFT_VERSION: 4.2
  OTHER_SWIFT_FLAGS: '-Xfrontend -debug-time-function-bodies'
targets:
  ExCamera:
    type: application
    platform: iOS
    sources: ExCamera
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.example.camera
        CODE_SIGN_STYLE: Manual
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: ExCamera/info.plist
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        CURRENT_PROJECT_VERSION: 1
      configs:
        Debug:
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development me.example.camera
          DEBUG_INFORMATION_FORMAT: dwarf
        AdHoc:
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc me.example.camera
    prebuildScripts:
      - name: Run LicensePlist
        script: ${SRCROOT}/Pods/LicensePlist/license-plist --output-path ${PRODUCT_NAME}/Settings.bundle
      - name: Run SwiftLint
        script: ${SRCROOT}/Pods/SwiftLint/swiftlint
      - name: Run R.swift
        script: ${SRCROOT}/Pods/R.swift/rswift generate ${SRCROOT}/ExCamera
    dependencies:
      - carthage: Cartography
  ExCameraTests:
    type: bundle.unit-test
    platform: iOS
    sources: ExCameraTests
    settings:
      INFOPLIST_FILE: ExCameraTests/info.plist
      CODE_SIGN_STYLE: Automatic
      TEST_HOST: ${BUILT_PRODUCTS_DIR}/ExCameraTests.app