name: Camera
configs:
  Debug: debug
  Release: release
options:
  defaultConfig: Release
  deploymentTarget: [iOS]
  developmentLanguage: en
  xcodeVersion: 11.0
  transitivelyLinkDependencies: true
  groupSortPosition: bottom
  minimumXcodeGenVersion: 2.15.1
attributes: {
}
configFiles:
  Debug: Configs/Development.xcconfig
  Release: Configs/Production.xcconfig
schemes:
  Development:
    build:
      targets:
        Camera: all
    run:
      config: Debug
      commandLineArguments:
        "-FIRAnalyticsDebugEnabled": true
      environmentVariables:
        - variable: OS_ACTIVITY_MODE
          value: disable
          isEnabled: true
    test:
      config: Debug
      targets:
        - name: CameraTests
    profile:
      config: Debug
    archive:
      config: Debug
  Production:
    build:
      targets:
        Camera: all
    run:
      config: Release
      commandLineArguments:
        "-noFIRAnalyticsDebugEnabled": true
      environmentVariables:
        - variable: OS_ACTIVITY_MODE
          value: disable
          isEnabled: false
    test:
      config: Release
      targets:
        - name: CameraTests
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
targets:
  Camera:
    type: application
    platform: iOS
    sources:
      - Camera
    configFiles:
      Debug: Configs/App-Development.xcconfig
      Release: Configs/App-Production.xcconfig
    dependencies:
      - target: Environments
      - target: Logger
      - carthage: DIKit
      - carthage: Cartography
    prebuildScripts:
      - name: Run LicensePlist
        script: |
          ${SRCROOT}/Pods/LicensePlist/license-plist --output-path Camera/Settings.bundle --config-path license_plist.yml --single-page
      - name: Run SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            swiftlint --no-cache
          fi
      - name: Run SwiftGen
        script: |
          if which swiftgen >/dev/null; then
            swiftgen
          fi
      - name: Run DIKitGen
        script: |
          if which dikitgen >/dev/null; then
            dikitgen ${SRCROOT}/Camera --exclude Carthage > Camera/AppResolver.generated.swift
          fi
      - name: Run CopyBundleResources
        script: |
          version=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "Camera/Info.plist")
          /usr/libexec/PlistBuddy -c "Set PreferenceSpecifiers:1:DefaultValue $version" "Camera/Settings.bundle/Root.plist"
  Environments:
    type: framework
    platform: iOS
    sources: Environments
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.excamera.environments
      INFOPLIST_FILE: Environments/Info.plist
  Logger:
    type: framework
    platform: iOS
    sources:
      - Logger
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.excamera.logger
      INFOPLIST_FILE: Logger/Info.plist
  CameraTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - CameraTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.excamera.tests
      INFOPLIST_FILE: CameraTests/Info.plist
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Camera
      - carthage: Quick
      - carthage: Nimble