fastlane_require 'dotenv'

before_all do
  Dotenv.overload '.env'
end

default_platform(:ios)

platform :ios do

  before_all do
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end

  # e.g) bundle exec fastlane ios bootstrap
  desc "Execute commands necessary for development"
  lane :bootstrap do
    setup_project
  end

  # e.g) bundle exec fastlane ios beta
  desc "Submit a new Beta Build to Fabric"
  lane :beta do
    TARGETS = JSON.parse(`xcodebuild -list -json -project ../ExCamera.xcodeproj`)['project']['targets']

    TARGETS.each do |target|
      backup_file(path: "./#{target}/Info.plist")
    end

    increment_build_number

    build_app(export_method: "ad-hoc")

    crashlytics(
      crashlytics_path: "./Pods/Crashlytics/iOS/Crashlytics.framework",
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      notes: "",
      ipa_path: "./ExCamera.ipa"
    )

    upload_symbols_to_crashlytics

    clean_build_artifacts

    TARGETS.each do |target|
      restore_file(path: "./#{target}/Info.plist")
    end
  end

  # e.g) bundle exec fastlane ios release
  desc "Deploy a new version to the App Store"
  lane :release do
  end

  # e.g) bundle exec fastlane ios test
  desc "Runs all the tests"
  lane :test do
    scan
  end

  # e.g) bundle exec fastlane ios certs
  desc "Execute certificates issuance"
  lane :certificates do
    match(app_identifier: "me.example.camera", type: "development", force_for_new_devices: true)
    match(app_identifier: "me.example.camera", type: "appstore", force_for_new_devices: true)
  end

  def setup_project
    # Mintfile を使った場合、パッケージのリンクを行ってくれないので dikitgen がそのまま使えない
    # Mintfile で $ mint bootstrap が済んだ場合は実際にもう一回インストールを行わず、リンクだけを行う
    # project.yml の prebuildScripts でビルドスクリプトを記述している
    sh 'cd .. && which dikitgen >/dev/null || mint install ishkawa/DIKit dikitgen && dikitgen ExCamera --exclude Carthage > ExCamera/AppResolver.generated.swift'

    sh 'cd .. && swiftgen'
    sh 'cd .. && xcodegen'

    cocoapods
    carthage(
      command: 'build',
      platform: 'ios',
      cache_builds: true,
      use_binaries: false
    )
  end

  def replace_fabric_api_key_from_info_plist
    update_info_plist(
      plist_path: "./ExCamera/Info.plist",
      block: proc do |plist|
        plist["Fabric"]["APIKey"] = ENV['CRASHLYTICS_API_TOKEN']
      end
    )
  end

end